[pytest]
# Look for features in the current directory (.)
bdd_features_base_dir = .
# Add current directory to python path for local imports
pythonpath = .
markers =
    smoke: vital functional tests
    attendance: attendance module tests
    regression: marks tests as regression (deselect with '-m "not regression"')